"""update user model with server defaults

Revision ID: e373fa5c31a5
Revises: 720d84446bae
Create Date: 2025-07-12 12:43:54.754309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # faisal


# revision identifiers, used by Alembic.
revision: str = 'e373fa5c31a5'
down_revision: Union[str, Sequence[str], None] = '720d84446bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'"), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
